- .gitignore
- Makefile
- README.md
- guestmetric/guestmetric.go
- guestmetric/guestmetric_linux.go
- guestmetric/guestmetric_test.go
- xe-daemon/xe-daemon.go
- xenstore/xenstore.go
- xenstoreclient/xenstore.go
- xenstoreclient/xenstore_test.go
This is the reviewed and tested Go guest agent for XenServer Linux guests.
Go guest agent is a static linked binary without any dependency (e.g. Bash or Python execution environment) with below benefits: 
1. Cross platform, Go version works well with all kinds Linux distributions (i386 and x86_64) with the porting ability to arm, FreeBSD, Darwin OS etc.
2. Standalone binary, works well with some restricted environment for example, CoreOS and Boot2Docker Linux
3. Easy to maintain and structured design, with Golang's nature
Change history:
1: Refined Rob Robert's comments.
2: Add unit test for xenstoreclient and refact folder structure.
3: Refined codes according to Robert's comments
4: To run 32bit xe-guest-agent in Linux 64bit OS(eg, CoreOS):
we need 4.1 - Switch to ip/ifconfig CLI tool …
> CP-11399: Go Linux guest agent for XenServer

- mk/xe-linux-distribution
latest Boot2Docker lsb_relase output
```
Boot2Docker 1.6.2 (TCL 6.3); master : 68777f2
```
/usr/sbin/xe-linux-distribution cannot handle "(TCL 6.3)" string
This commit is to fix this issue.
> CA-173690: Guest Agent: /usr/sbin/xe-linux-distribution cannot works in latest boot2docker.

- xenstoreclient/xenstore.go
The first commit is an attempted bug-fix. Please review that this now restores the intended behaviour of the write-cache.
The second commit is a proposed optimisation. I personally don't see the need for the 2-minute timeout for the cache. But perhaps I am missing something, so please correct me if there's a reason we need this.
> Make xe-daemon generate less xenstore traffic

- feature/FeatureIPSetting.go
As packing issue, we cannot use net since it will cause 64 bit system install issue.
Remove network address check, since XAPI already check the IP to make sure it is a valid IP address.
We should not do duplicate work here.
Signed-off-by: root <cheng.zhang@citrix.com>
> CP-16740: Remove dependency on net package

- Makefile
- mk/Makefile.deb
- mk/Makefile.rpm
- mk/Makefile.tgz
- system/system.go
- xe-daemon/xe-daemon.go
If the guest is suspended and then resumed or migrated, trigger a
refresh to repopulate the xenstore entries (since the guest will have a
new domid).
Without doing this, XAPI thinks that the guest does not have PV drivers
installed and will refuse to do a vbd-plug operation until then next
refresh by the guest agent.
Tested with newer Linux x86_64 and i386 guests and an older Linux i386 guest.
> CA-202608: Trigger refresh after system resume

- guestmetric/guestmetric_linux.go
if ip address end with new line without space, then the 
regular expression cannot match it. 
This case happen when use manully change network name in  Ubuntu 16
> Fix IP address end with new line

- mk/Makefile.deb
- mk/Makefile.rpm
- mk/Makefile.tgz
- mk/debian/control
- mk/xe-linux-distribution.init
- xe-daemon/xe-daemon.go
1. Package architecture-specific binaries for debian
2. Mute xe-daemon logs unless debug flag is set
3. Correct tgz packaging
3. Let xe-linux-distribution handle its PID file safely
> CA-220438: Minor improvements for xe-guest-utilities

- mk/Citrix.repo
- mk/citrix.list
- mk/debian/xe-guest-utilities.postinst
- mk/xe-guest-utilities.spec.in
Signed-off-by: Kun Ma <kun.ma@citrix.com>
Since we want to use branding-xenserver to brand all files. And those post process string(DISTRO) should be distinguish with the branded file. So replace '@' with '^'.
> CP-20237: Replace place-holder for DISTRO to '^'

- mk/xe-linux-distribution
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>
Tested by hand, the new RE works:
\# echo 'NeoKylin Linux Security OS V5.0 (Update8)' | sed -rn 's/^Neo[kK]ylin Linux [^0-9]+([0-9]+)\.?([0-9]+)?.*$/distro=neokylin;major=\1;minor=\2;/gp;'
distro=neokylin;major=5;minor=0;
\# echo 'Neokylin Linux Security OS Server release V5 (Santiago)' | sed -rn 's/^Neo[kK]ylin Linux [^0-9]+([0-9]+)\.?([0-9]+)?.*$/distro=neokylin;major=\1;minor=\2;/gp;'
distro=neokylin;major=5;minor=;
\# echo 'NeoKylin Linux Advanced Server release 6.5 (Berryllium)' | sed -rn 's/^Neo[kK]ylin Linux [^0-9]+([0-9]+)\.?([0-9]+)?.*$/distro=neokylin;major=\1;minor=\2;/gp;'
distro=neokylin;major=6;minor=5;
\# echo 'NeoKylin Linux Advanced Server release 7.0' | sed -rn 's/^Neo[kK]ylin Linux …
> CA-261230: add support NeoKylin 5.0 for alternative version

- Makefile
Relative path linking makes the group of xenstore utilities
more portable.
> Make xenstore utilities link to relative path

- mk/xe-linux-distribution.service
- mk/xen-vcpu-hotplug.rules
So this package is safe to be installed on Non-xen hosts.
> Take effect only on Xen virtualization

- Makefile
The file has a '.tgz' suffix, but was not actually compressed.
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> Properly compress the generated tgz file.

- mk/xen-vcpu-hotplug.rules
The guest agent installs a udev rule which triggers when a CPU is added.
The rule checks whether it is running under Xen using xenstore-exists,
and then onlines the vCPU.
This is problematic during boot because xenstore-exists tries to connect
to xenstore by accessing /proc/xen/xenbus which is on a separate mount
that either doesn't exist at that point or isn't usable. The result is a
hang and systemd-udev-settle.service stalling boot.
Fix it by simply checking for the presence of /dev/xen/xenbus to
determine whether the agent is running under Xen.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> CA-333687: Fix boot hang caused by CPU hotplug rule

- mk/xe-linux-distribution
The format of /etc/centos-release has changed to not include any additional
content after the version number, which was not being matched by our existing
regular expression. Update the expression so it works with both the original
(e.g. CentOS 7 format), and the newer format.
Signed-off-by: Alex Brett <alex.brett@citrix.com>
> CA-349929: Fix handling of /etc/centos-release for CentOS 8.3+

- mk/xe-linux-distribution
"CentOS Stream" is specified in /etc/centos-release, along with only the
major version. Updates the expression in the identify_redhat function to
include a check for this distribution and prevent daemon errors.
> Add CentOS Stream to xe-linux-distribution

- Makefile
If the GOARCH environment variable is defined, use it as the arch
for the name of the tarball produced in build/dist/
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
Without this, `GOARCH=386 make` produces a tarball that contains `x86_64` in the filename.
> Fix name of tarball based on GOARCH

- mk/xe-linux-distribution
Add support to xe-guest-utilities for the Linux distribution "Rocky", which can be treated as successor of CentOS Linux.
> Rocky Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with America's top enterprise Linux distribution now that its downstream partner has shifted direction. It is under intensive development by the community. Rocky Linux is led by Gregory Kurtzer, founder of the CentOS project. Release Candidate 1 is now available for testing.
(Source: https://rockylinux.org/)
> Support for Rocky Linux distribution

- Makefile
- go.mod
- go.sum
- guestmetric/guestmetric_linux.go
- xe-daemon/xe-daemon.go
- xenstore/xenstore.go
Due to changes in the module system, go 1.16 no longer tolerates including
local folders via
import "../system"
Now, on is expected to reference the name of the parent project
import "xe-guest-utilities/system"
Additional go now expects a go.mod file with listing of external dependencies
and a go.sum with hashes of those.
And go no longer allows '.' within paths that aren't URLs.
> Update for building with go 1.16

- README.md
The building instructions don't work with the mentioned go version (1.6.4)
It might just be a spelling mistake:
current version `go1.16.4` => `go 1.6.4`  Released 2016-02-17, eol since 2017-08-24
But regardless i have drafted new building instructions
During my testing the latest version I could get to build was `go 1.10`
* `go 1.9` doesn't have `strings.Builder` needed in `xenstore/xenstore.go:126`
* `go 1.6.4` lacks math/bits in the standart lib, required to build current golang.org/x/sys/unix
> Update Building instructions for new go versions

- mk/xe-linux-distribution
The /etc/os-release file is a standardized format containing operating
system identification data. Like lsb_release it allows to get
distribution information but uses a simple file format which is meant to
be sourced in a script.
See also:
https://www.freedesktop.org/software/systemd/man/os-release.html
> Support generic distributions using os-release

- guestmetric/guestmetric_linux.go
When you launch an Arch VM on xcp-ng, you have an interface where the name starts with enX, not enx, which means that the main interface is not found.
> Fix archlinux guestmetric for ip interfaces

- mk/testcases/slackware-15.0
- mk/xe-linux-distribution
- mk/xe-linux-distribution-test
Removed identify_slackware() from  xe-linux-distribution
Added call to identify_os_release() in xe-linux-distribution-test
Added Slackware 15.0 test case via identify_os_release()
Signed-off-by: mco-system <michael.costa@mcos.nc>
> chore: Added Slackware 15.0 test case via identify_os_release

- guestmetric/guestmetric_linux.go
Noticed this small issue when reading the code - don't have hardware to test it, but it seems pretty straighforward
> Fix identification of blockdev block size

- mk/xe-guest-utilities.spec.in
As some vendors have started to phase out 'chkconfig', an outdated package management solution. we have decided to fully adopt systemd. Consequently, we have made some adjustments to prioritize systemd-based management for distribution that support,
while utilizing SystemV, particular chkconfig, for the remaining ones, to ensure compatibility.
Signed-off-by: Lunfan Zhang Lunfan.Zhang@citrix.com
> CA-381643 Replace systemV Services control with systemd

- CODEOWNERS
Update the Code Owner to add jing.peng@cloud.com and lunfan.zhang@cloud.com to the guest utilities Repo
Update the Code Owner of xihuan.yang@citrix.com and liulin@citrix.com from @citrx.com to @cloud.com
> CP-50465 Update the Code Owner of guest utilities

- guestmetric/guestmetric_linux.go
In certain cases, if a physical volume (PV) is created but not associated with a volume group (VG), the output of `output, err := runCmd("pvs", "--noheadings", "--units", "b", path)` will be:
`/dev/xvda1 lvm2 a-- 2097664B 2097664B`
This output structure can lead to an out-of-bounds error when attempting to access the free space of the PV via parts[5], and guest agent will crash.
This PR ensures accurate retrieval of PV free space and filesystem information using the --options parameter, preventing potential index mismatch errors.
> CP-49568 Guest agent fails to collect disk metrics when PV is not associated with a VG

- mk/xe-linux-distribution.service
Add a service dependency on the network-online target to ensure the guest agent service starts after the network is online and collects network metrics during the first loop.
> CP-53590 IP Address Metrics Not Reported Immediately After Reboot

- README.md
- mk/xe-linux-distribution.service
- There is some typo in the README which should be refined
- `wants `should be `Wants ` in service unit, although it will not block service to startup and work but it will not take effect
> CP-54734 README and Service unit refinement
