xenserver/xe-guest-utilities

guestmetric/guestmetric_linux.go
=> CP-11399: Ignore blkid errors

.travis.yml, README.md
Without go test and coverage for now.
Signed-off-by: Robert Breker <robert.breker@citrix.com>
=> Add basic Travis CI configuration

mk/Makefile.deb, mk/Makefile.rpm, mk/Makefile.tgz
=> CA-172846: Tools installed out of date when a Linux VM is freshly installed from templates

xe-daemon/syslog.go, xe-daemon/xe-daemon.go
1. Add syslog writer
2. Use ioutil.WriteFile to write pid
3. Refine logger.Printf usage
=> CA-172369: Golang Guest Agent doesn't use print the logs into guest machine syslog

Makefile, mk/Makefile.deb, mk/Makefile.rpm, mk/Makefile.tgz, syslog/syslog.go, xe-daemon/xe-daemon.go
=> CA-172369: Separate syslog package and use "-v" build flag.

xenstoreclient/xenstore.go, xenstoreclient/xenstore_test.go
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
=> CP-16739: Make watch in status

xenstoreclient/xenstore.go
Signed-off-by: chengz <cheng.zhang@citrix.com>
=> CP-16739: Fix compile error of logger points

Makefile, feature/FeatureIPSetting.go, mk/Makefile.deb, mk/Makefile.rpm, mk/Makefile.tgz, xe-daemon/xe-daemon.go, xenstoreclient/xenstore.go
This pull request is to:
1. Fix deadlock mentioned in https://lkml.org/lkml/2016/5/17/196
2. Fix watch event issue as if we watch on a dir, all change event of the dir keys need to go into the same chain.
3. Add Directory interface so we can query the subkeys
4. Add framework to set IP address 
5. Operations like read can return error as file not exist, add error return in DO logic
=> CP-15244: Add framework for set IP address featrue

feature/FeatureIPSetting.go, xenstoreclient/xenstore.go
Signed-off-by: chengz <cheng.zhang@citrix.com>
=> CP-15244: Add OS type check and IP Parse

feature/FeatureIPSetting.go, feature/FeatureIPSetting_test.go, xenstoreclient/xenstore_test.go
Signed-off-by: ChengZ <cheng.zhang@citrix.com>
=> CP-16740: Add UT for setting history

xe-daemon/xe-daemon.go, xenstoreclient/xenstore.go
Update the xenstore cache and delete not available record
Signed-off-by: Liang Dai <liang.dai1@citrix.com>
=> CA-240982: Xencenter shows IP address of interface of VM even if I remove IP from the interface

guestmetric/guestmetric_linux.go, xe-daemon/xe-daemon.go
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
=> CA-243280: Report mac for guest VM

mk/xe-linux-distribution
Signed-off-by: Wei Xie <Wei.Xie@citrix.com>
=> CA-244770: Add support for Kylin_Linux 7.2 and Kylin_Linux 6.5

mk/debian/changelog
Signed-off-by: Kun Ma <kun.ma@citrix.com>
=> CP-20237: Since branding-xenserver can not handle digital data, change place-holder @822DATE@ to @BUILD_DATE@

mk/xe-linux-distribution
Signed-off-by: Wei Xie <Wei.Xie@citrix.com>
=> CA-244770: Use extended regex parameter in sed.

mk/xe-linux-distribution
=> CP-21862: Make guest tools identify RedFlag Linux.

mk/xe-linux-distribution
=> CA-250696: DDK build number is optional.

mk/xe-linux-distribution
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>
@xiewei20082008 @cheng-z please help to review.
=> CP-22496: add support of NeoKylin 5.0 (Update8)

mk/xe-linux-distribution
Please merge to master and create new tag, e.g. v7.8.0, then I can create PR for guest agent feature branch
=> add support NeoKylin 5.0 (Update8)

mk/xe-linux-distribution
Please help to create new tag v7.9.0 too
=> CA-261230: add support NeoKylin 5.0 for alternative version 

guestmetric/guestmetric_linux.go, xenstore/xenstore.go, xenstoreclient/xenstore.go
=> CP-23647: Add SRIOV VF IP collection

guestmetric/guestmetric_linux.go, xenstore/xenstore.go, xenstoreclient/xenstore.go
=> CP-26664: Add SRIOV VF IP collection

Makefile
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>
=> CP-25986: Add xenstore-list command

xenstore/xenstore.go
=> CP-27273: Enhance the printing format of guest_utilities.xs_list for HCL using.

mk/testcases/sle-15, mk/xe-linux-distribution, mk/xe-linux-distribution-test
Signed-off-by: Yuan Ren <yuan.ren@citrix.com>
=> CP-30014: Add support for SUSE enterprise Linux 15 (#4)

.gitignore, analyze.py, security-check.sh
1. Introduce gosec to check the security issue of this project.
2. Integrate the check in jenkins pipeline. (will do in the pipeline repo)
Signed-off-by: Yang Qian <yang.qian@citrix.com>
=> Check the security of the project

analyze.py, security-check.sh
Output the formatted issues to a file
Signed-off-by: Yang Qian <yang.qian@citrix.com>
=> output formatted issues

Makefile, xenstore/xenstore.go, xenstoreclient/xenstore.go
=> CP-31808: implement xenstore-ls

xenstoreclient/xenstore.go
=> CA-323837: Fix wrong permission order

Makefile, mk/debian/rules, xenstore/xenstore.go, xenstoreclient/xenstore.go
=> CP-31842: implement xenstore-chmod for golang guest xenstore

Makefile, mk/debian/rules, xenstore/xenstore.go, xenstoreclient/xenstore.go
=> CP-31968: implement xenstore-watch for golang guest xenstore

xenstoreclient/xenstore_test.go
=> fix test for xenstore-watch

syslog/syslog.go, xe-daemon/xe-daemon.go
Set the default priority of logger to debug instead of notice.
=> CA-286041: xe-daemon log spam

CODEOWNERS
Signed-off-by: Min Li<min.li1@citrix.com>
=> Add CODEOWNERS file for setting default code reviewers.

LICENSE
Signed-off-by: gangj <gang.ji@citrix.com>
=> CP-33374: update license

mk/xe-linux-distribution
=> CP-33708: identify gooroom OS

mk/xe-linux-distribution
Added AlamaLinux to the list of detectable distributions.
=> Adds AlmaLinux Support

mk/xe-linux-distribution
Signed-off-by: Min Li <min.li1@citrix.com>
=> Fix typo of Alma Linux.

mk/xe-linux-distribution, mk/xe-linux-distribution-test, mk/xe-linux-distribution.init
There was a mix of tabs and spaces so I replaced the tabs with spaces (8
spaces for one tab, except when there were already spaces inside the
tab space).
Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>
=> Fix indentation: remove tabs

README.md
Signed-off-by: Xihuan Yang <xihuan.yang@citrix.com>
=> Add details about how to build

guestmetric/guestmetric_linux.go
Signed-off-by: Xihuan Yang <xihuan.yang@citrix.com>
=> CA-352996: Get meminfo_free metric from MemAvailable in /proc/meminfo

README.md
Signed-off-by: Xihuan Yang <xihuan.yang@citrix.com>
=> Modify XenServer to Citrix Hypervisor in README.md

mk/xe-linux-distribution
Added Slackware support to xe-linux-distribution
=> feat: Slackware support

CODEOWNERS
Signed-off-by: Xihuan Yang <xihuan.yang@citrix.com>
=> Add Lin Liu into the Code Owner

README.md
This documents the xenstore keys updated by `xe-daemon'
=> Detail collected informations in README

mk/Citrix.repo, mk/Makefile.deb, mk/Makefile.rpm, mk/Makefile.tgz, mk/citrix.list, mk/debian/rules, mk/debian/xe-guest-utilities.postinst, mk/debian/xe-guest-utilities.prerm, mk/xe-guest-utilities.spec.in
Signed-off-by: t_minghuih <minghui.hu@citrix.com>
=> CP-41119:Remove Citrix.Repo from xe-guest-utilities

LICENSE
Remove the word 'holding' from the copyright of LICENSE.
=> CP-42912: Remove the word 'holding' from the copyright of LICENSE.

xe-daemon/xe-daemon.go
Extend pm_freeze_timeout to 5 min when the value of pm_freeze_timeout  is  not customized.
Refer to the Oracle Suspend issue: [8.3 Suspend Error During Storage Live Migration (oracle.com)](https://docs.oracle.com/cd/E64076_01/E85146/html/vmrns-bugs-3.4.4-26289880.html)
=> CP-41689 Extend pm_freeze_timeout to 5 min when guest agent startup
